services:

    document-generator:
        networks:
            - default
            - caddy
        labels:
            caddy: ${UI_SERVER}
            caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  # Add caddy as an external network.
  caddy:
    external: true